---
project_name: microservices-infrastructure
project_path: /opt/{{ project_name }}
docker_compose_version: "2.20.0"

ssh_private_key_path: "{{ lookup('env', 'HOME') }}/.ssh/deploy_rsa"
ssh_public_key_path: "{{ lookup('env', 'HOME') }}/.ssh/deploy_rsa.pub"

docker_network: db-network
docker_compose_path: "{{ project_path }}/docker-compose-files"

deployment_user: deploy
deployment_group: deploy

log_directory: /var/log/{{ project_name }}
backup_directory: /var/backups/{{ project_name }}

timezone: UTC

